type Query {
    accountsList : [BankAccount],
    getBankAccountById (id:String) : BankAccount,
    getCustomers : [Customer]
}

type Mutation {
    addBankAccount(bankAccount : BankAccountDTO) : BankAccount,
    updateAccountBank(id : String, bankAccount : BankAccountDTO) : BankAccount,
    deleteAccountBank(id : String) : Boolean
}



type BankAccount {
    id : String,
    createdAt : Float,
    balance : Float,
    currency : String,
    type : String,
    customer : Customer
}

type Customer {
    id: ID,
    name : String,
    bankAccounts : [BankAccount]
}

input BankAccountDTO {
    balance : Float,
    currency : String,
    type : String
}